name: Twilio Sned
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
env:
    TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
    TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
    TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
permissions:
  contents: read
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(234)5678901'
          toPhoneNumber: '+1(234)3334444'
          message: 'Hello from Twilio'
